# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catalog_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/catalog/'),
        ),
        migrations.AddField(
            model_name='category',
            name='catalog_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
